Jkpi 15 metric lib
janis-commerce/metrics pull request #1
Opened 2022-06-06 21:13 UTC by mdanelutti

Link al ticket
[JKPI-4](https://fizzmod.atlassian.net/browse/JKPI-4) | [JKPI-15](https://fizzmod.atlassian.net/browse/JKPI-15)

Descripción del requerimiento
Crear un package que permita guardar métricas, para mas detalle [JKPI-4](https://fizzmod.atlassian.net/browse/JKPI-4)...  

Descripción de la solución
Se hizo el package pedido respetando la estructura planteada

Datos a tener en cuenta
De todo lo requerido en el ticket la parte de tracker se omitió por el momento para métricas no es necesario.

Changelog

Added
- Lib to create metrics
- github workflows

2022-06-08 14:44 UTC, guillecipri approved these changes

2022-06-09 18:47 UTC, gastonpereyra commented on .eslintrc.js
> +'use strict';
Podriamos aprovechar de agregar que soporte lo nuevo de JS, como `?`.

2022-06-09 18:48 UTC, gastonpereyra commented on .github/workflows/build-status.yml
> +    strategy:
Yo iriá derecho a 14.x para arriba

2022-06-09 18:50 UTC, gastonpereyra commented on .huskyrc.json
> +{
Podriamos crear el package ya con las ultimas versiones de Husky (en las nuevas cambia este archivo por una carpeta)

2022-06-09 18:54 UTC, gastonpereyra commented on lib/firehose-instance.js
> +class FirehoseInstance {
Se podría exportar directamente.

2022-06-09 19:00 UTC, gastonpereyra commented on lib/index.js
> +'use strict';
Para evitar este Archivo pasamanos, para evitarlo se puede cambiar en `package.json` en `main`  cual va a ser el archivo principal en este caso el de`metric`

2022-06-09 19:14 UTC, gastonpereyra commented on lib/metric.js
> +	static get serverlessConfiguration() {
El `get` lo pondría entre los primeros métodos

2022-06-09 19:14 UTC, gastonpereyra requested changes
Deje algunos comentarios

2022-06-14 21:05 UTC, gastonpereyra approved these changes

2022-06-15 20:10 UTC, jormaechea requested changes

2022-06-15 20:10 UTC, jormaechea commented on lib/metric.js
> +	static async _add(metricsBatches, attempts = 0) {
Epa, que onda con esto? Si un batch falla va a intentar reenviar todo 3 veces? O sea que algunas métricas se van a enviar 3 veces, otras ninguna y encima va a reportar todas como error?

Me suena a bug....

2022-06-15 20:10 UTC, jormaechea commented on package.json
> +		"uuid": "^7.0.3"
`uuid` ya no es mas una dependencia..

2022-06-21 19:29 UTC, jormaechea approved these changes

2022-06-21 19:30 UTC, merged